# Netlify konfigurationsfil

[build]
  base = "/"
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

# Environment variabler kan definieras här
[build.environment]
  NODE_VERSION = "20.11"
  NPM_VERSION = "10.2"

# För att hantera Netlify Forms
[build.processing.html]
  pretty_urls = true

# Använd Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"